First draft of blogpost "Taking advantage of CSS Custom Properties"
zonkytech/blog pull request #1
Opened 2017-02-16 19:35 UTC by BillyBigBurger

Draft for blog post titled: "Taking advantage of CSS Custom Properties" written.

2017-02-17 13:52 UTC, argelius requested changes
Lite kommentarer

2017-02-17 13:52 UTC, argelius commented on source/_posts/Taking-advantage-of-CSS-Custom-Properties.md
> +#### What are CSS Custom Properties?
h2

2017-02-17 13:52 UTC, argelius commented on source/_posts/Taking-advantage-of-CSS-Custom-Properties.md
> +The draft for [Custom CSS Properties](https://drafts.csswg.org/css-variables/) has existed for quite some time and since implementation for it started in [Microsoft Edge](https://developer.microsoft.
Förslag: "If you haven't looked" istället för "So if you haven't".

2017-02-17 13:52 UTC, argelius commented on source/_posts/Taking-advantage-of-CSS-Custom-Properties.md
> +    margin: var(--big-margin);
indent

2017-02-17 13:52 UTC, argelius commented on source/_posts/Taking-advantage-of-CSS-Custom-Properties.md
> +Variables are defined by prefixing our variable name with two dashes and can be accessed using the `var()` function. It is also possible to extends the properties when different styling is used in ot
extend

2017-02-17 13:52 UTC, argelius commented on source/_posts/Taking-advantage-of-CSS-Custom-Properties.md
> +   color:var(--span-color, red);
indent

2017-02-17 13:52 UTC, argelius commented on source/_posts/Taking-advantage-of-CSS-Custom-Properties.md
> +.my-div
parentes på samma rad

2017-02-17 13:52 UTC, argelius commented on source/_posts/Taking-advantage-of-CSS-Custom-Properties.md
> +While similar functionally has existed in pre-processors such as [SASS](http://sass-lang.com/) and [LESS](http://lesscss.org/) for a while (with arguably better looking syntax as well), the main diff
functionality

2017-02-17 13:52 UTC, argelius commented on source/_posts/Taking-advantage-of-CSS-Custom-Properties.md
> +While similar functionally has existed in pre-processors such as [SASS](http://sass-lang.com/) and [LESS](http://lesscss.org/) for a while (with arguably better looking syntax as well), the main diff
preprocessors

2017-02-17 13:52 UTC, argelius commented on source/_posts/Taking-advantage-of-CSS-Custom-Properties.md
> +#### Using `@media` rules
h2

2017-02-17 13:56 UTC, argelius commented
@BillyBigBurger 

Hittade lite stavfel. Högsta nivån av överskrifter ska vara h2 eftersom titeln är h1.

Skriver du möjligtvis med en Mac? Apostroferna är någon sorts Unicode-tecken men jag antar att de är mer korrekta än vanliga apostrofer.

Innehållet är bra! CSS-variabler är det bästa sen skivat bröd!

2017-02-20 12:44 UTC, BillyBigBurger commented
Tackar för feedbacken @argelius , har fixat dina kommentarer.

Ja jag skrev delvis på en Mac och delvis på en linux-maskin. Men är ` inte vanliga "back-ticks", eller är det nåt jag missar?

2017-02-24 09:33 UTC, argelius approved these changes

2017-02-24 09:34 UTC, argelius commented
@BillyBigBurger Hmm. Nu ser jag dem inte laengre men naer jag anvaende en annan dator var apostroferna annorlunda aen den vanliga ASCII-apostrofen.

2017-02-24 09:34 UTC, argelius commented
:shipit:

2017-03-03 14:00 UTC, merged